import { FilesetResolver, PoseLandmarker } from "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1";

const $ = (selector) => document.querySelector(selector);
const video = $("#camera");
const canvas = $("#game-canvas");
const ctx = canvas.getContext("2d");
const screens = document.querySelectorAll(".screen");
const state = { mode: "menu", landmarker: null, landmarks: null, lastVideoTime: -1, score: 0, combo: 0, misses: 0, roundStart: 0, roundLength: 5000, baselineHip: null, sound: true, animation: 0 };
const poses = [
  { name: "CÁNH CHIM", hint: "Duỗi thẳng hai tay sang ngang", type: "arms", target: [170, 170] },
  { name: "LỰC SĨ", hint: "Gập khuỷu tay thành góc vuông", type: "arms", target: [90, 90] },
  { name: "CSGT", hint: "Một tay thẳng, một tay vuông", type: "arms", target: [170, 90] },
  { name: "NGỒI XUỐNG", hint: "Hạ thấp hông để né tường", type: "squat" },
];
let task = poses[0];

function showScreen(id) { screens.forEach((screen) => screen.classList.toggle("active", screen.id === id)); }
function setMode(mode) { state.mode = mode; showScreen(`${mode}-screen`); $("#play-hud").classList.toggle("hidden", mode !== "playing"); $("#timer-wrap").classList.toggle("hidden", mode !== "playing"); }
function setStatus(text, active = false) { $("#camera-status").innerHTML = `<i style="background:${active ? '#52ffb8' : '#45f3ff'}"></i> ${text}`; }
function updateHud() { $("#score").textContent = String(state.score).padStart(4, "0"); $("#combo").textContent = `×${state.combo}`; $("#pose-name").textContent = task.name; $("#pose-hint").textContent = task.hint; $("#lives").textContent = `CÒN ${Math.max(0, 3 - state.misses)} LƯỢT SAI`; }
function tone(freq, length = 0.08) { if (!state.sound) return; const audio = new AudioContext(); const oscillator = audio.createOscillator(); const gain = audio.createGain(); oscillator.frequency.value = freq; gain.gain.setValueAtTime(.045, audio.currentTime); gain.gain.exponentialRampToValueAtTime(.0001, audio.currentTime + length); oscillator.connect(gain).connect(audio.destination); oscillator.start(); oscillator.stop(audio.currentTime + length); }
function angle(a, b, c) { const ab = Math.atan2(a.y - b.y, a.x - b.x); const cb = Math.atan2(c.y - b.y, c.x - b.x); let result = Math.abs((ab - cb) * 180 / Math.PI); return result > 180 ? 360 - result : result; }
function poseMatches(lm) { if (!lm) return false; if (task.type === "squat") { const hip = (lm[23].y + lm[24].y) / 2; return state.baselineHip !== null && hip > state.baselineHip + .09; } const left = angle(lm[11], lm[13], lm[15]); const right = angle(lm[12], lm[14], lm[16]); const [targetL, targetR] = task.target; const close = (value, target) => Math.abs(value - target) < 27; return (close(left, targetL) && close(right, targetR)) || (close(left, targetR) && close(right, targetL)); }
function chooseTask() { task = poses[Math.floor(Math.random() * poses.length)]; updateHud(); }
function beginRound() { state.roundStart = performance.now(); chooseTask(); }
function startGame() { cancelAnimationFrame(state.animation); state.score = 0; state.combo = 0; state.misses = 0; updateHud(); setMode("calibration"); let seconds = 3; $("#calibration-count").textContent = seconds; const calibration = setInterval(() => { seconds -= 1; $("#calibration-count").textContent = seconds || "GO"; if (seconds <= 0) { clearInterval(calibration); state.baselineHip = state.landmarks ? (state.landmarks[23].y + state.landmarks[24].y) / 2 : .56; setMode("playing"); beginRound(); tone(740); state.animation = requestAnimationFrame(gameLoop); } }, 850); }
function endGame() { cancelAnimationFrame(state.animation); setMode("gameover"); $("#final-score").textContent = String(state.score).padStart(4, "0"); const best = Number(localStorage.getItem("wall-game-best") || 0); const record = state.score > best; if (record) localStorage.setItem("wall-game-best", String(state.score)); $("#record-note").textContent = record ? "KỶ LỤC MỚI! Bạn đã làm rất tốt." : `Kỷ lục cá nhân: ${String(Math.max(best, state.score)).padStart(4, "0")}`; tone(180, .24); }
function drawPose(lm) { const w = canvas.width, h = canvas.height; const links = [[11,12],[11,13],[13,15],[12,14],[14,16],[11,23],[12,24],[23,24],[23,25],[25,27],[24,26],[26,28]]; ctx.save(); ctx.scale(-1, 1); ctx.translate(-w, 0); ctx.lineWidth = Math.max(3, w / 260); ctx.lineCap = "round"; ctx.shadowBlur = 15; ctx.shadowColor = "#45f3ff"; ctx.strokeStyle = "#45f3ff"; for (const [a,b] of links) { ctx.beginPath(); ctx.moveTo(lm[a].x*w,lm[a].y*h); ctx.lineTo(lm[b].x*w,lm[b].y*h); ctx.stroke(); } ctx.fillStyle="#fff"; for (const index of [11,12,13,14,15,16,23,24,25,26]) { ctx.beginPath();ctx.arc(lm[index].x*w,lm[index].y*h,Math.max(3,w/170),0,Math.PI*2);ctx.fill(); } ctx.restore(); }
function drawWall(progress) { const w = canvas.width, h = canvas.height; const scale = .18 + progress * 1.1; const ww = w * scale, hh = h * scale; ctx.save(); ctx.translate(w/2,h/2); ctx.strokeStyle = progress > .8 ? "#ff44c7" : "#45f3ff"; ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=24;ctx.lineWidth=Math.max(3,w/260);ctx.strokeRect(-ww/2,-hh/2,ww,hh); ctx.globalAlpha=.14;ctx.fillStyle=ctx.strokeStyle;ctx.fillRect(-ww/2,-hh/2,ww,hh);ctx.restore(); }
function gameLoop(now) { if (state.mode !== "playing") return; ctx.clearRect(0,0,canvas.width,canvas.height); if (state.landmarks) drawPose(state.landmarks); const elapsed = now - state.roundStart; const progress = Math.min(elapsed / state.roundLength, 1); drawWall(progress); $("#timer-fill").style.transform = `scaleX(${1-progress})`; if (progress >= 1) { if (poseMatches(state.landmarks)) { state.combo += 1; state.score += 100 + state.combo * 25; tone(880); beginRound(); } else { state.combo = 0; state.misses += 1; state.score = Math.max(0, state.score - 50); tone(250); if (state.misses >= 3) { updateHud(); endGame(); return; } beginRound(); } updateHud(); } state.animation = requestAnimationFrame(gameLoop); }
async function setupCamera() { try { setStatus("ĐANG KẾT NỐI"); const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "user", width: { ideal: 1280 }, height: { ideal: 720 } }, audio: false }); video.srcObject = stream; await video.play(); canvas.width = video.videoWidth; canvas.height = video.videoHeight; const vision = await FilesetResolver.forVisionTasks("https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/wasm"); state.landmarker = await PoseLandmarker.createFromOptions(vision, { baseOptions: { modelAssetPath: "https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task", delegate: "GPU" }, runningMode: "VIDEO", numPoses: 1 }); setStatus("CAMERA ĐÃ SẴN SÀNG", true); trackPose(); startGame(); } catch (error) { console.error(error); setStatus("KHÔNG THỂ MỞ CAMERA"); alert("Không thể mở camera. Hãy dùng HTTPS/localhost, cấp quyền camera và thử lại."); setMode("menu"); } }
function trackPose() { if (video.currentTime !== state.lastVideoTime && state.landmarker) { state.lastVideoTime = video.currentTime; const result = state.landmarker.detectForVideo(video, performance.now()); state.landmarks = result.landmarks?.[0] || null; } requestAnimationFrame(trackPose); }
$("#play-button").onclick = () => setMode("permission"); $("#camera-button").onclick = setupCamera; $("#again-button").onclick = startGame; $("#how-button").onclick = () => $("#instruction-modal").classList.remove("hidden"); $("#close-instructions").onclick = () => $("#instruction-modal").classList.add("hidden"); $("#instruction-play").onclick = () => { $("#instruction-modal").classList.add("hidden"); setMode("permission"); }; document.querySelectorAll(".back-button").forEach((button) => button.onclick = () => setMode("menu")); $("#sound-toggle").onclick = () => { state.sound = !state.sound; $("#sound-toggle").textContent = state.sound ? "♬" : "♩"; };
